
# There're not products available
GET http://localhost:8080/api/products
###

# Add new Product
POST http://localhost:8080/api/products
content-type: application/json

{
    "title": "Incredible Frozen Bacon",
    "price": 12,
    "thumbnail": "http://www.bacon.com"
}
###

# List Products
GET http://localhost:8080/api/products
###

# ProductById Not Found
GET http://localhost:8080/api/products/0
###

# ProductById
GET http://localhost:8080/api/products/1
###

# Update
PUT http://localhost:8080/api/products
content-type: application/json

{
    "id": 2,
    "title": "Updated Incredible Frozen Bacon",
    "price": 99,
    "thumbnail": "http://www.bacon.com"
}
###

# Partial Update
PATCH  http://localhost:8080/api/products/2/price
content-type: application/json

{
    "price": 999
}

###

# Delete
DELETE  http://localhost:8080/api/products/3
###

# List Products
GET http://localhost:8080/api/products
